---
title: "Report"
author: "Dominik Gulacsy"
date: "17/10/2020"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=F, message=FALSE, echo=FALSE, eval=TRUE}
library(tidyverse)
library(geosphere)
library(moments)
library(dplyr)
## Github Repo of Assignment: https://github.com/Julianna-szabo/DA_team_project
# Import data using paths
#setwd("C:/Users/Dominik/OneDrive - Central European University/1st_trimester/DA1/DA_team_project")
#esource="C:/Users/Dominik/OneDrive - Central European University/1st_trimester/DA1/DA_team_project"
# Import via URL
dp = read_csv('data/raw/dp.csv')
```

# Data collection


# Calculations for opening hours and distance from CEU

```{r, echo=FALSE eval=TRUE}
ceu = c(47.501348, 19.049375)
dp["dist_ceu"] = distm(data.matrix(dp[6:7]), ceu, fun = distHaversine)
distm(ceu, c(47.500386, 19.049434), fun=distHaversine)

get_interval <- function(open,close){
  intv = close-open
  if (intv < 0) {
    intv = as.difftime("24:00:00")-open+close
  }
  intv=as.numeric(as.difftime(intv,units = "hours"))/60
  return(intv)
}

dp$open_mins=mapply(get_interval, dp$open, dp$close)
```

# Descriptive Statistics

```{r, eval=TRUE}
library(dplyr)
dp_summary_stats_pizza <- summarise(dp,
          n= n(),
          mean = mean(x = price_marg),
          median = median(x = price_marg),
          min= min(price_marg),
          max = max(price_marg),
          sd = sd(price_marg),
          skew = skewness(price_marg))
dp_summary_stats_bev <- summarise(dp,
          n= n(),
          mean = mean(x = price_bev),
          median = median(x = price_bev),
          min= min(price_bev),
          max = max(price_bev),
          sd = sd(price_bev),
          skew = skewness(price_bev))

table_summary <- dp_summary_stats_pizza %>% add_row(dp_summary_stats_bev)
```

# Distributions
## Price of pizza margarite and beverage

```{r, echo=FALSE}
dp %>% 
  ggplot(aes(x=price_marg))+
  geom_histogram(binwidth = 200, fill= "coral2", col= "black")+
  theme_bw()+
  labs(x = 'Price of Margarita Pizza', y= 'Number of Pizzas', title = "Distribution of Price for Pizza")

dp %>% 
  ggplot(aes(x=price_bev))+
  geom_histogram(binwidth = 50, fill= "light blue", col= "black")+
  theme_bw()+
  labs(x = 'Price of 0.5L beverage', y= 'Number of Pizzas', title = "Distribution of Price for Beverage")
```

## Price distribution on-site vs delivery

```{r, echo=FALSE}
dp$category_f <- factor(dp$category)

ggplot(data = dp, aes(x = price_marg, fill = category_f))+
  geom_histogram(binwidth = 200, col = "black")+
  labs(x='Price of Margarita Pizza', y='Number of Pizzas', title = "Distribution of Price for On-site", fill= 'category')+
  facet_wrap(~category_f)
```

# T-test
## Hypothesis
Null mean(on-site)=mean(delivery)
Alternative mean(on-site) not = mean(delivery)

```{r, echo=FALSE}
price_offline <- dp$price_marg[dp$category=="On-site"]
price_online <- dp$price_marg[dp$category=="Delivery"]

t.test(price_offline,price_online, alternative = "two.sided")
```

# Summary and Conclusion